### PR TITLE
*fixing a bug where getting DNS records fails because of malformed URL

### PR DESCRIPTION
**Pull request by tad3j**

### CODE REVIEW

**Comment by unxp** [comment]
@tad3j Can you update the pull request? It has basically no changes

**Comment by tad3j** [comment]
Sorry, I noticed that my IDE automatically changed spacing, so changes are hard to spot.

Else I've added two changes on lines 
https://github.com/gellu/godaddy-api-client/pull/6/files#diff-1d42f3435f8d12d5407733b1127eb299R1414
https://github.com/gellu/godaddy-api-client/pull/6/files#diff-1d42f3435f8d12d5407733b1127eb299R1422

**Comment by unxp** [comment]
Great, thanks. Can somebody merge this? :) I need this big fixed :)

**Comment by tad3j** [comment]
I've been using this commit on production since I have made the change and I had no problems.

Until it gets merged you can try to use this in your composer file

`"gellu/godaddy-api-client": "dev-master#c91c03a15d38b8a841be03f78d755ed055293b7c",`

**Comment by unxp** [comment]
Ping @gellu

**Pull request merged**
